### ISSUE TITLE
Hide tabbar but wrong in navigation

### ISSUE THREAD

**Issue by aaveidt** [suarezluis/react-navigation-selective-tab-bar#2]
If i have 3 tab inside of stacknavigation
Stack1: Home
Stack2: TabNavigator
        [Main, Search, Profile]

i choose to hide Search tab.
After `navigation.navigate('Search')` from `Home` , it point to Search tab correctly. but if i press back button, it go back to Main tab ??!.

It's wrong, it supposed to get back to previous tab which is `Home`, not `Main` tab.

**Comment by suarezluis** [comment]
Have you tried with the stock tab bar navigator? I suspect this is the behavior on the stock tab bar navigation as well

**Comment by suarezluis** [comment]
Issue closed due to inactivity
